services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: 'host'
    restart: 'unless-stopped'
    volumes:
      - config:/config
      - cache:/cache
      - /media:/media
    environment:
      - JELLYFIN_PublishedServerUrl=http://raspberrypi.local:8096
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  config:
  cache: