services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: 'unless-stopped'
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - media:/media
    environment:
      - JELLYFIN_PublishedServerUrl=http://raspberrypi.local:8096
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '8096:8096'
      - '8920:8920'
      #- '1900:1900/udp' in use by home assistant
      - '7359:7359/udp'

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Berlin
    volumes:
      - jellyseerr-config:/app/config
    ports:
      - 5055:5055

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - prowlarr-config:/config
    ports:
      - 9696:9696

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - radarr-config:/config
      - media:/media
    ports:
      - 7878:7878

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - sonarr-config:/config
      - media:/media
    ports:
      - 8989:8989

  # Note: Set the inet_exposure = 4 to access to the SABnzbd UI

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - sabnzbd-config:/config
      - media:/downloads
      - sabnzbd-incomplete-downloads:/incomplete-downloads
    ports:
      - 8080:8080

volumes:
  media:
  jellyfin-config:
  jellyfin-cache:
  jellyseerr-config:
  prowlarr-config:
  radarr-config:
  sonarr-config:
  sabnzbd-config:
  sabnzbd-incomplete-downloads: