services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: host
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Berlin
    ports:
      - 5055:5055
    volumes:
      - config:/app/config

volumes:
  config: